int a = 2;
int b = 1;
int c = 4;
int d = 8;
int e = 1;
int f = 9;
int max = 0;
if(a>max) max=a;
if(b>max) max=b;
if(c>max) max=c;
if(d>max) max=d;
if(e>max) max=e;
if(f>max) max=f;
Console.Write("max = ");
Console.WriteLine(max);
